// <auto-generated />
using System;
using System.Text.Json;
using BridgeTech.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BridgeTech.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BridgeTech.Api.Domain.Entities.Certificate", b =>
                {
                    b.Property<Guid>("CertificateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("certificate_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CertificateHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("certificate_hash")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("IssuedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("module_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("CertificateId")
                        .HasName("pk_certificates");

                    b.HasIndex("CertificateHash")
                        .IsUnique()
                        .HasDatabaseName("ix_certificates_certificate_hash");

                    b.HasIndex("ModuleId")
                        .HasDatabaseName("ix_certificates_module_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_certificates_user_id");

                    b.HasIndex("UserId", "ModuleId")
                        .IsUnique()
                        .HasDatabaseName("ix_certificates_user_id_module_id");

                    b.ToTable("certificates", "public");
                });

            modelBuilder.Entity("BridgeTech.Api.Domain.Entities.Enrollment", b =>
                {
                    b.Property<Guid>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("enrollment_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("EnrolledAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enrolled_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("module_id");

                    b.Property<short>("ProgressPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("progress_percent");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("EnrollmentId")
                        .HasName("pk_enrollments");

                    b.HasIndex("ModuleId")
                        .HasDatabaseName("ix_enrollments_module_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_enrollments_user_id");

                    b.HasIndex("UserId", "ModuleId")
                        .IsUnique()
                        .HasDatabaseName("ix_enrollments_user_id_module_id");

                    b.ToTable("enrollments", "public");
                });

            modelBuilder.Entity("BridgeTech.Api.Domain.Entities.Exercise", b =>
                {
                    b.Property<Guid>("ExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("module_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<JsonDocument>("VerificationCriteria")
                        .HasColumnType("jsonb")
                        .HasColumnName("verification_criteria");

                    b.Property<short>("VerificationType")
                        .HasColumnType("smallint")
                        .HasColumnName("verification_type");

                    b.HasKey("ExerciseId")
                        .HasName("pk_exercises");

                    b.HasIndex("ModuleId")
                        .HasDatabaseName("ix_exercises_module_id");

                    b.HasIndex("VerificationCriteria")
                        .HasDatabaseName("ix_exercises_verification_criteria");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("VerificationCriteria"), "gin");

                    b.ToTable("exercises", "public");
                });

            modelBuilder.Entity("BridgeTech.Api.Domain.Entities.ExerciseSubmission", b =>
                {
                    b.Property<Guid>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<string>("GithubRepoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("github_repo_url");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("SubmissionId")
                        .HasName("pk_exercise_submissions");

                    b.HasIndex("ExerciseId")
                        .HasDatabaseName("ix_exercise_submissions_exercise_id");

                    b.HasIndex("Status", "SubmittedAt")
                        .HasDatabaseName("ix_exercise_submissions_status_submitted_at")
                        .HasFilter("status = 0");

                    b.HasIndex("UserId", "ExerciseId")
                        .HasDatabaseName("ix_exercise_submissions_user_id_exercise_id");

                    b.ToTable("exercise_submissions", "public");
                });

            modelBuilder.Entity("BridgeTech.Api.Domain.Entities.Lesson", b =>
                {
                    b.Property<Guid>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("module_id");

                    b.Property<short>("OrderIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("order_index");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("LessonId")
                        .HasName("pk_lessons");

                    b.HasIndex("ModuleId", "OrderIndex")
                        .HasDatabaseName("ix_lessons_module_id_order_index");

                    b.ToTable("lessons", "public");
                });

            modelBuilder.Entity("BridgeTech.Api.Domain.Entities.Module", b =>
                {
                    b.Property<Guid>("ModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("module_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<short>("OrderIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("order_index");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ModuleId")
                        .HasName("pk_modules");

                    b.HasIndex("OrderIndex")
                        .HasDatabaseName("ix_modules_order_index");

                    b.ToTable("modules", "public");
                });

            modelBuilder.Entity("BridgeTech.Api.Domain.Entities.Quiz", b =>
                {
                    b.Property<Guid>("QuizId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("quiz_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("module_id");

                    b.Property<short>("PassingScore")
                        .HasColumnType("smallint")
                        .HasColumnName("passing_score");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("QuizId")
                        .HasName("pk_quizzes");

                    b.HasIndex("ModuleId")
                        .HasDatabaseName("ix_quizzes_module_id");

                    b.ToTable("quizzes", "public");
                });

            modelBuilder.Entity("BridgeTech.Api.Domain.Entities.QuizAnswer", b =>
                {
                    b.Property<Guid>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("answer_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("attempt_id");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<Guid>("OptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("option_id");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.HasKey("AnswerId")
                        .HasName("pk_quiz_answers");

                    b.HasIndex("AttemptId")
                        .HasDatabaseName("ix_quiz_answers_attempt_id");

                    b.HasIndex("OptionId")
                        .HasDatabaseName("ix_quiz_answers_option_id");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_quiz_answers_question_id");

                    b.ToTable("quiz_answers", "public");
                });

            modelBuilder.Entity("BridgeTech.Api.Domain.Entities.QuizAttempt", b =>
                {
                    b.Property<Guid>("AttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("attempt_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<bool?>("Passed")
                        .HasColumnType("boolean")
                        .HasColumnName("passed");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uuid")
                        .HasColumnName("quiz_id");

                    b.Property<short?>("Score")
                        .HasColumnType("smallint")
                        .HasColumnName("score");

                    b.Property<DateTimeOffset>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("AttemptId")
                        .HasName("pk_quiz_attempts");

                    b.HasIndex("QuizId")
                        .HasDatabaseName("ix_quiz_attempts_quiz_id");

                    b.HasIndex("UserId", "QuizId")
                        .HasDatabaseName("ix_quiz_attempts_user_id_quiz_id");

                    b.ToTable("quiz_attempts", "public");
                });

            modelBuilder.Entity("BridgeTech.Api.Domain.Entities.QuizOption", b =>
                {
                    b.Property<Guid>("OptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("option_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("IsCorrect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_correct");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("option_text");

                    b.Property<short>("OrderIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("order_index");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uuid")
                        .HasColumnName("quiz_id");

                    b.HasKey("OptionId")
                        .HasName("pk_quiz_options");

                    b.HasIndex("QuizId")
                        .HasDatabaseName("ix_quiz_options_quiz_id");

                    b.HasIndex("QuestionId", "OrderIndex")
                        .HasDatabaseName("ix_quiz_options_question_id_order_index");

                    b.ToTable("quiz_options", "public");
                });

            modelBuilder.Entity("BridgeTech.Api.Domain.Entities.QuizQuestion", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("question_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<short>("OrderIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("order_index");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("question_text");

                    b.Property<short>("QuestionType")
                        .HasColumnType("smallint")
                        .HasColumnName("question_type");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uuid")
                        .HasColumnName("quiz_id");

                    b.HasKey("QuestionId")
                        .HasName("pk_quiz_questions");

                    b.HasIndex("QuizId", "OrderIndex")
                        .HasDatabaseName("ix_quiz_questions_quiz_id_order_index");

                    b.ToTable("quiz_questions", "public");
                });

            modelBuilder.Entity("BridgeTech.Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("first_name");

                    b.Property<string>("GithubUsername")
                        .HasMaxLength(39)
                        .HasColumnType("character varying(39)")
                        .HasColumnName("github_username");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<short>("Role")
                        .HasColumnType("smallint")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("GithubUsername")
                        .HasDatabaseName("ix_users_github_username")
                        .HasFilter("github_username IS NOT NULL");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_users_role");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", "public");
                });

            modelBuilder.Entity("BridgeTech.Api.Domain.Entities.VideoSummary", b =>
                {
                    b.Property<Guid>("VideoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("video_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AiSummary")
                        .HasColumnType("text")
                        .HasColumnName("ai_summary");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<string>("Transcript")
                        .HasColumnType("text")
                        .HasColumnName("transcript");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("video_url");

                    b.HasKey("VideoId")
                        .HasName("pk_video_summaries");

                    b.HasIndex("LessonId")
                        .HasDatabaseName("ix_video_summaries_lesson_id");

                    b.ToTable("video_summaries", "public");
                });

            modelBuilder.Entity("BridgeTech.Api.Domain.Entities.Certificate", b =>
                {
                    b.HasOne("BridgeTech.Api.Domain.Entities.Module", "Module")
                        .WithMany("Certificates")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_certificates_modules_module_id");

                    b.HasOne("BridgeTech.Api.Domain.Entities.User", "User")
                        .WithMany("Certificates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_certificates_users_user_id");

                    b.Navigation("Module");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BridgeTech.Api.Domain.Entities.Enrollment", b =>
                {
                    b.HasOne("BridgeTech.Api.Domain.Entities.Module", "Module")
                        .WithMany("Enrollments")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_enrollments_modules_module_id");

                    b.HasOne("BridgeTech.Api.Domain.Entities.User", "User")
                        .WithMany("Enrollments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_enrollments_users_user_id");

                    b.Navigation("Module");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BridgeTech.Api.Domain.Entities.Exercise", b =>
                {
                    b.HasOne("BridgeTech.Api.Domain.Entities.Module", "Module")
                        .WithMany("Exercises")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exercises_modules_module_id");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("BridgeTech.Api.Domain.Entities.ExerciseSubmission", b =>
                {
                    b.HasOne("BridgeTech.Api.Domain.Entities.Exercise", "Exercise")
                        .WithMany("Submissions")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exercise_submissions_exercises_exercise_id");

                    b.HasOne("BridgeTech.Api.Domain.Entities.User", "User")
                        .WithMany("ExerciseSubmissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exercise_submissions_users_user_id");

                    b.Navigation("Exercise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BridgeTech.Api.Domain.Entities.Lesson", b =>
                {
                    b.HasOne("BridgeTech.Api.Domain.Entities.Module", "Module")
                        .WithMany("Lessons")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lessons_modules_module_id");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("BridgeTech.Api.Domain.Entities.Quiz", b =>
                {
                    b.HasOne("BridgeTech.Api.Domain.Entities.Module", "Module")
                        .WithMany("Quizzes")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quizzes_modules_module_id");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("BridgeTech.Api.Domain.Entities.QuizAnswer", b =>
                {
                    b.HasOne("BridgeTech.Api.Domain.Entities.QuizAttempt", "Attempt")
                        .WithMany("Answers")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quiz_answers_quiz_attempts_attempt_id");

                    b.HasOne("BridgeTech.Api.Domain.Entities.QuizOption", "Option")
                        .WithMany("Answers")
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quiz_answers_quiz_options_option_id");

                    b.HasOne("BridgeTech.Api.Domain.Entities.QuizQuestion", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quiz_answers_quiz_questions_question_id");

                    b.Navigation("Attempt");

                    b.Navigation("Option");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("BridgeTech.Api.Domain.Entities.QuizAttempt", b =>
                {
                    b.HasOne("BridgeTech.Api.Domain.Entities.Quiz", "Quiz")
                        .WithMany("Attempts")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quiz_attempts_quizzes_quiz_id");

                    b.HasOne("BridgeTech.Api.Domain.Entities.User", "User")
                        .WithMany("QuizAttempts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quiz_attempts_users_user_id");

                    b.Navigation("Quiz");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BridgeTech.Api.Domain.Entities.QuizOption", b =>
                {
                    b.HasOne("BridgeTech.Api.Domain.Entities.QuizQuestion", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quiz_options_quiz_questions_question_id");

                    b.HasOne("BridgeTech.Api.Domain.Entities.Quiz", "Quiz")
                        .WithMany()
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quiz_options_quizzes_quiz_id");

                    b.Navigation("Question");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("BridgeTech.Api.Domain.Entities.QuizQuestion", b =>
                {
                    b.HasOne("BridgeTech.Api.Domain.Entities.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quiz_questions_quizzes_quiz_id");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("BridgeTech.Api.Domain.Entities.VideoSummary", b =>
                {
                    b.HasOne("BridgeTech.Api.Domain.Entities.Lesson", "Lesson")
                        .WithMany("VideoSummaries")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_video_summaries_lessons_lesson_id");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("BridgeTech.Api.Domain.Entities.Exercise", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("BridgeTech.Api.Domain.Entities.Lesson", b =>
                {
                    b.Navigation("VideoSummaries");
                });

            modelBuilder.Entity("BridgeTech.Api.Domain.Entities.Module", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("Enrollments");

                    b.Navigation("Exercises");

                    b.Navigation("Lessons");

                    b.Navigation("Quizzes");
                });

            modelBuilder.Entity("BridgeTech.Api.Domain.Entities.Quiz", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("BridgeTech.Api.Domain.Entities.QuizAttempt", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("BridgeTech.Api.Domain.Entities.QuizOption", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("BridgeTech.Api.Domain.Entities.QuizQuestion", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Options");
                });

            modelBuilder.Entity("BridgeTech.Api.Domain.Entities.User", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("Enrollments");

                    b.Navigation("ExerciseSubmissions");

                    b.Navigation("QuizAttempts");
                });
#pragma warning restore 612, 618
        }
    }
}
