@host = http://localhost:5174

### Check PostgreSQL connection
GET {{host}}/api/database/status
Accept: application/json

### Get modules from PostgreSQL
GET {{host}}/api/modules
Accept: application/json