using BridgeTech.Api.Domain.Entities;
using BridgeTech.Api.Domain.Enums;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace BridgeTech.Api.Data.Configurations;

internal static class EntityConfigurationHelpers
{
    // All schema tables use UUID primary keys generated by PostgreSQL. Keeping
    // this shared setup in one method prevents small mapping differences.
    public static void ConfigureId<TEntity>(EntityTypeBuilder<TEntity> builder, string tableName, string keyName)
        where TEntity : class
    {
        builder.ToTable(tableName);
        builder.HasKey(keyName);
        builder.Property<Guid>(keyName).HasDefaultValueSql("gen_random_uuid()");
    }
}

internal sealed class UserConfiguration : IEntityTypeConfiguration<User>
{
    public void Configure(EntityTypeBuilder<User> builder)
    {
        // Users are uniquely identified by both email and username because both
        // values are used during authentication and account management.
        EntityConfigurationHelpers.ConfigureId(builder, "users", nameof(User.UserId));
        builder.Property(x => x.Username).HasMaxLength(50).IsRequired();
        builder.Property(x => x.FirstName).HasMaxLength(254).IsRequired();
        builder.Property(x => x.LastName).HasMaxLength(254).IsRequired();
        builder.Property(x => x.Email).HasMaxLength(254).IsRequired();
        builder.Property(x => x.PasswordHash).HasMaxLength(255).IsRequired();
        builder.Property(x => x.GithubUsername).HasMaxLength(39);
        builder.Property(x => x.Role).HasConversion<short>().IsRequired();
        builder.Property(x => x.CreatedAt).HasDefaultValueSql("now()");
        builder.Property(x => x.UpdatedAt).HasDefaultValueSql("now()");
        builder.HasIndex(x => x.Email).IsUnique();
        builder.HasIndex(x => x.Username).IsUnique();
        builder.HasIndex(x => x.GithubUsername).HasFilter("github_username IS NOT NULL");
        builder.HasIndex(x => x.Role);
    }
}

internal sealed class ModuleConfiguration : IEntityTypeConfiguration<Module>
{
    public void Configure(EntityTypeBuilder<Module> builder)
    {
        // Modules are displayed in their configured order on the learning dashboard.
        EntityConfigurationHelpers.ConfigureId(builder, "modules", nameof(Module.ModuleId));
        builder.Property(x => x.Title).HasMaxLength(200).IsRequired();
        builder.Property(x => x.OrderIndex).HasDefaultValue((short)0).IsRequired();
        builder.Property(x => x.CreatedAt).HasDefaultValueSql("now()");
        builder.Property(x => x.UpdatedAt).HasDefaultValueSql("now()");
        builder.HasIndex(x => x.OrderIndex);
    }
}

internal sealed class LessonConfiguration : IEntityTypeConfiguration<Lesson>
{
    public void Configure(EntityTypeBuilder<Lesson> builder)
    {
        // Deleting a module also deletes its lessons, matching ON DELETE CASCADE.
        EntityConfigurationHelpers.ConfigureId(builder, "lessons", nameof(Lesson.LessonId));
        builder.Property(x => x.Title).HasMaxLength(200).IsRequired();
        builder.Property(x => x.OrderIndex).HasDefaultValue((short)0).IsRequired();
        builder.Property(x => x.CreatedAt).HasDefaultValueSql("now()");
        builder.Property(x => x.UpdatedAt).HasDefaultValueSql("now()");
        builder.HasOne(x => x.Module).WithMany(x => x.Lessons).HasForeignKey(x => x.ModuleId).OnDelete(DeleteBehavior.Cascade);
        builder.HasIndex(x => new { x.ModuleId, x.OrderIndex });
    }
}

internal sealed class VideoSummaryConfiguration : IEntityTypeConfiguration<VideoSummary>
{
    public void Configure(EntityTypeBuilder<VideoSummary> builder)
    {
        // Video summaries belong to lessons and are removed with their parent lesson.
        EntityConfigurationHelpers.ConfigureId(builder, "video_summaries", nameof(VideoSummary.VideoId));
        builder.Property(x => x.VideoUrl).HasMaxLength(500).IsRequired();
        builder.Property(x => x.GeneratedAt).HasDefaultValueSql("now()");
        builder.HasOne(x => x.Lesson).WithMany(x => x.VideoSummaries).HasForeignKey(x => x.LessonId).OnDelete(DeleteBehavior.Cascade);
        builder.HasIndex(x => x.LessonId);
    }
}

internal sealed class QuizConfiguration : IEntityTypeConfiguration<Quiz>
{
    public void Configure(EntityTypeBuilder<Quiz> builder)
    {
        // A quiz belongs to one module and stores the score required to pass.
        EntityConfigurationHelpers.ConfigureId(builder, "quizzes", nameof(Quiz.QuizId));
        builder.Property(x => x.Title).HasMaxLength(200).IsRequired();
        builder.Property(x => x.PassingScore).IsRequired();
        builder.Property(x => x.CreatedAt).HasDefaultValueSql("now()");
        builder.HasOne(x => x.Module).WithMany(x => x.Quizzes).HasForeignKey(x => x.ModuleId).OnDelete(DeleteBehavior.Cascade);
        builder.HasIndex(x => x.ModuleId);
    }
}

internal sealed class QuizQuestionConfiguration : IEntityTypeConfiguration<QuizQuestion>
{
    public void Configure(EntityTypeBuilder<QuizQuestion> builder)
    {
        // Questions are returned in order when a student starts a quiz.
        EntityConfigurationHelpers.ConfigureId(builder, "quiz_questions", nameof(QuizQuestion.QuestionId));
        builder.Property(x => x.QuestionText).HasMaxLength(500).IsRequired();
        builder.Property(x => x.QuestionType).HasConversion<short>().IsRequired();
        builder.Property(x => x.OrderIndex).HasDefaultValue((short)0).IsRequired();
        builder.HasOne(x => x.Quiz).WithMany(x => x.Questions).HasForeignKey(x => x.QuizId).OnDelete(DeleteBehavior.Cascade);
        builder.HasIndex(x => new { x.QuizId, x.OrderIndex });
    }
}

internal sealed class QuizOptionConfiguration : IEntityTypeConfiguration<QuizOption>
{
    public void Configure(EntityTypeBuilder<QuizOption> builder)
    {
        // Options reference both the quiz and question to mirror the SQL schema.
        EntityConfigurationHelpers.ConfigureId(builder, "quiz_options", nameof(QuizOption.OptionId));
        builder.Property(x => x.OptionText).HasMaxLength(500).IsRequired();
        builder.Property(x => x.IsCorrect).HasDefaultValue(false).IsRequired();
        builder.Property(x => x.OrderIndex).HasDefaultValue((short)0).IsRequired();
        builder.HasOne(x => x.Quiz).WithMany().HasForeignKey(x => x.QuizId).OnDelete(DeleteBehavior.Cascade);
        builder.HasOne(x => x.Question).WithMany(x => x.Options).HasForeignKey(x => x.QuestionId).OnDelete(DeleteBehavior.Cascade);
        builder.HasIndex(x => new { x.QuestionId, x.OrderIndex });
    }
}

internal sealed class QuizAttemptConfiguration : IEntityTypeConfiguration<QuizAttempt>
{
    public void Configure(EntityTypeBuilder<QuizAttempt> builder)
    {
        // Attempts connect a user to a quiz and support reporting by either side.
        EntityConfigurationHelpers.ConfigureId(builder, "quiz_attempts", nameof(QuizAttempt.AttemptId));
        builder.Property(x => x.StartedAt).HasDefaultValueSql("now()").IsRequired();
        builder.HasOne(x => x.User).WithMany(x => x.QuizAttempts).HasForeignKey(x => x.UserId).OnDelete(DeleteBehavior.Cascade);
        builder.HasOne(x => x.Quiz).WithMany(x => x.Attempts).HasForeignKey(x => x.QuizId).OnDelete(DeleteBehavior.Cascade);
        builder.HasIndex(x => new { x.UserId, x.QuizId });
        builder.HasIndex(x => x.QuizId);
    }
}

internal sealed class QuizAnswerConfiguration : IEntityTypeConfiguration<QuizAnswer>
{
    public void Configure(EntityTypeBuilder<QuizAnswer> builder)
    {
        // Each answer records the selected option and the grading result.
        EntityConfigurationHelpers.ConfigureId(builder, "quiz_answers", nameof(QuizAnswer.AnswerId));
        builder.Property(x => x.IsCorrect).IsRequired();
        builder.HasOne(x => x.Attempt).WithMany(x => x.Answers).HasForeignKey(x => x.AttemptId).OnDelete(DeleteBehavior.Cascade);
        builder.HasOne(x => x.Question).WithMany(x => x.Answers).HasForeignKey(x => x.QuestionId).OnDelete(DeleteBehavior.Cascade);
        builder.HasOne(x => x.Option).WithMany(x => x.Answers).HasForeignKey(x => x.OptionId).OnDelete(DeleteBehavior.Cascade);
        builder.HasIndex(x => x.AttemptId);
        builder.HasIndex(x => x.QuestionId);
    }
}

internal sealed class ExerciseConfiguration : IEntityTypeConfiguration<Exercise>
{
    public void Configure(EntityTypeBuilder<Exercise> builder)
    {
        // JSONB keeps verification rules flexible for different GitHub checks.
        EntityConfigurationHelpers.ConfigureId(builder, "exercises", nameof(Exercise.ExerciseId));
        builder.Property(x => x.Title).HasMaxLength(200).IsRequired();
        builder.Property(x => x.VerificationType).HasConversion<short>().IsRequired();
        builder.Property(x => x.VerificationCriteria).HasColumnType("jsonb");
        builder.Property(x => x.CreatedAt).HasDefaultValueSql("now()");
        builder.HasOne(x => x.Module).WithMany(x => x.Exercises).HasForeignKey(x => x.ModuleId).OnDelete(DeleteBehavior.Cascade);
        builder.HasIndex(x => x.ModuleId);
        builder.HasIndex(x => x.VerificationCriteria).HasMethod("gin");
    }
}

internal sealed class ExerciseSubmissionConfiguration : IEntityTypeConfiguration<ExerciseSubmission>
{
    public void Configure(EntityTypeBuilder<ExerciseSubmission> builder)
    {
        // The partial pending index supports the background verification worker.
        EntityConfigurationHelpers.ConfigureId(builder, "exercise_submissions", nameof(ExerciseSubmission.SubmissionId));
        builder.Property(x => x.GithubRepoUrl).HasMaxLength(500).IsRequired();
        builder.Property(x => x.Status).HasConversion<short>().HasDefaultValue(SubmissionStatus.Pending).IsRequired();
        builder.Property(x => x.SubmittedAt).HasDefaultValueSql("now()").IsRequired();
        builder.HasOne(x => x.Exercise).WithMany(x => x.Submissions).HasForeignKey(x => x.ExerciseId).OnDelete(DeleteBehavior.Cascade);
        builder.HasOne(x => x.User).WithMany(x => x.ExerciseSubmissions).HasForeignKey(x => x.UserId).OnDelete(DeleteBehavior.Cascade);
        builder.HasIndex(x => new { x.UserId, x.ExerciseId });
        builder.HasIndex(x => new { x.Status, x.SubmittedAt }).HasFilter("status = 0");
    }
}

internal sealed class EnrollmentConfiguration : IEntityTypeConfiguration<Enrollment>
{
    public void Configure(EntityTypeBuilder<Enrollment> builder)
    {
        // The unique user/module index prevents duplicate enrollments.
        EntityConfigurationHelpers.ConfigureId(builder, "enrollments", nameof(Enrollment.EnrollmentId));
        builder.Property(x => x.Status).HasConversion<short>().HasDefaultValue(EnrollmentStatus.Active).IsRequired();
        builder.Property(x => x.ProgressPercent).HasDefaultValue((short)0).IsRequired();
        builder.Property(x => x.EnrolledAt).HasDefaultValueSql("now()").IsRequired();
        builder.HasOne(x => x.Module).WithMany(x => x.Enrollments).HasForeignKey(x => x.ModuleId).OnDelete(DeleteBehavior.Cascade);
        builder.HasOne(x => x.User).WithMany(x => x.Enrollments).HasForeignKey(x => x.UserId).OnDelete(DeleteBehavior.Cascade);
        builder.HasIndex(x => new { x.UserId, x.ModuleId }).IsUnique();
        builder.HasIndex(x => x.UserId);
        builder.HasIndex(x => x.ModuleId);
    }
}

internal sealed class CertificateConfiguration : IEntityTypeConfiguration<Certificate>
{
    public void Configure(EntityTypeBuilder<Certificate> builder)
    {
        // A certificate is unique per user/module and by its public verification hash.
        EntityConfigurationHelpers.ConfigureId(builder, "certificates", nameof(Certificate.CertificateId));
        builder.Property(x => x.CertificateHash).HasColumnType("char(64)").IsFixedLength().IsRequired();
        builder.Property(x => x.IssuedAt).HasDefaultValueSql("now()").IsRequired();
        builder.HasOne(x => x.User).WithMany(x => x.Certificates).HasForeignKey(x => x.UserId).OnDelete(DeleteBehavior.Cascade);
        builder.HasOne(x => x.Module).WithMany(x => x.Certificates).HasForeignKey(x => x.ModuleId).OnDelete(DeleteBehavior.Cascade);
        builder.HasIndex(x => new { x.UserId, x.ModuleId }).IsUnique();
        builder.HasIndex(x => x.CertificateHash).IsUnique();
        builder.HasIndex(x => x.UserId);
    }
}